#!/bin/bash

echo "🧪 TESTE DE SEPARAÇÃO DE DADOS - ADMIN vs ESTUDANTE"
echo "===================================================="
echo ""

# Verificar se o servidor está rodando
if ! curl -s http://localhost:5173 > /dev/null; then
    echo "❌ ERRO: Frontend não está rodando em localhost:5173"
    echo "Execute: cd frontend && npm run dev"
    exit 1
fi

echo "✅ Frontend rodando em http://localhost:5173"
echo ""

echo "📋 TESTES DE SEPARAÇÃO DE DADOS"
echo "================================"
echo ""

echo "1️⃣ TESTE DE ISOLAMENTO DE DECKS:"
echo "   a) Faça login como ADMIN (admin@studypro.com / Admin@123)"
echo "   b) Vá para: /admin/flashcards (gestão de decks)"
echo "   c) Anote quantos decks existem do admin"
echo "   d) DELETE todos os decks do admin"
echo "   e) Faça logout e login como ESTUDANTE (aluno@example.com / aluno123)"
echo "   f) Vá para: /my-flashcards (aba 'DECKS')"
echo "   g) ✓ VERIFICAR: Decks do estudante devem PERMANECER intactos"
echo "   h) ✓ VERIFICAR: Estudante não deve ver decks que eram do admin"
echo ""

echo "2️⃣ TESTE DE ISOLAMENTO DE FLASHCARDS:"
echo "   a) Ainda como ESTUDANTE, vá para aba 'FLASHCARDS'"
echo "   b) Anote quantos flashcards existem do estudante"
echo "   c) Faça logout e login como ADMIN"
echo "   d) Vá para: /admin/flashcards/cards"
echo "   e) Filtre por 'Autor: Estudante' (ou nome do aluno)"
echo "   f) DELETE todos os flashcards do admin (não do estudante!)"
echo "   g) Faça logout e login como ESTUDANTE"
echo "   h) ✓ VERIFICAR: Flashcards do estudante devem PERMANECER"
echo "   i) ✓ VERIFICAR: Estudante não vê mais flashcards que eram do admin"
echo ""

echo "3️⃣ TESTE DE CRIAÇÃO - ADMIN:"
echo "   a) Login como ADMIN"
echo "   b) Vá para: /admin/flashcards/cards/new"
echo "   c) Teste criação de cada um dos 7 tipos:"
echo "      🔵 BÁSICO - Teste exemplo automático"
echo "      🟢 BÁSICO INVERTIDO - Teste com informação extra"  
echo "      🟡 LACUNAS (Cloze) - Use: {{c1::Brasil}} é um {{c2::país}}"
echo "      🟣 MÚLTIPLA ESCOLHA - 4 opções com explicação"
echo "      🔴 VERDADEIRO/FALSO - Com explicação detalhada"
echo "      🟦 DIGITE RESPOSTA - Com dica opcional"
echo "      🟠 OCLUSÃO IMAGEM - Upload imagem + áreas"
echo "   d) ✓ VERIFICAR: Todos os tipos salvam corretamente"
echo "   e) ✓ VERIFICAR: Admin pode definir status (público/privado)"
echo ""

echo "4️⃣ TESTE DE CRIAÇÃO - ESTUDANTE:"
echo "   a) Login como ESTUDANTE"
echo "   b) Vá para: /student/flashcards/new"
echo "   c) Teste criação dos mesmos 7 tipos do admin"
echo "   d) ✓ VERIFICAR: Interface idêntica ao admin"
echo "   e) ✓ VERIFICAR: Estudante pode definir PRIVADO/PÚBLICO"
echo "   f) ✓ VERIFICAR: Flashcards criados só aparecem para o estudante"
echo ""

echo "5️⃣ TESTE FUNCIONALIDADES ANKI COMPLETAS:"
echo "========================================="
echo "   CLOZE MÚLTIPLO:"
echo "   a) Crie flashcard tipo LACUNAS com: 'O {{c1::Brasil}} fica na {{c2::América}} do {{c3::Sul}}'"
echo "   b) ✓ VERIFICAR: Deve gerar 3 flashcards separados:"
echo "      - Card 1: 'O [___] fica na América do Sul'"
echo "      - Card 2: 'O Brasil fica na [___] do Sul'"
echo "      - Card 3: 'O Brasil fica na América do [___]'"
echo ""
echo "   IMPORT/EXPORT:"
echo "   c) Teste importação de arquivo .apkg"
echo "   d) Teste exportação em todos os formatos:"
echo "      - JSON: Estrutura completa dos dados"
echo "      - CSV: Formato tabular para planilhas"
echo "      - ANKI: Formato nativo Anki"
echo "      - .APKG: Pacote completo importável"
echo ""
echo "   TIPOS ESPECÍFICOS:"
echo "   e) ✓ BÁSICO INVERTIDO: Deve criar automaticamente card reverso"
echo "   f) ✓ MÚLTIPLA ESCOLHA: 4 opções + explicação da resposta"
echo "   g) ✓ OCLUSÃO IMAGEM: Áreas clicáveis + respostas personalizadas"
echo "   h) ✓ DIGITE RESPOSTA: Campo input + dica opcional"
echo ""

echo "6️⃣ TESTE DE PERMISSÕES AVANÇADAS:"
echo "=================================="
echo "   a) Login como ADMIN, crie flashcard PRIVADO"
echo "   b) Login como ESTUDANTE"
echo "   c) ✓ VERIFICAR: Estudante NÃO vê flashcard privado do admin"
echo "   d) Admin cria flashcard PÚBLICO"
echo "   e) ✓ VERIFICAR: Estudante VÊ flashcard público do admin"
echo "   f) Estudante cria flashcard PRIVADO"
echo "   g) Login como ADMIN, filtre por autor do estudante"
echo "   h) ✓ VERIFICAR: Admin VÊ flashcard privado do estudante (supervisão)"
echo "   i) ✓ VERIFICAR: Admin NÃO pode editar flashcard do estudante"
echo ""

echo "7️⃣ TESTE DE DECK MANAGEMENT:"
echo "============================"
echo "   a) Estudante cria deck pessoal"
echo "   b) Estudante adiciona seus próprios flashcards ao deck"
echo "   c) ✓ VERIFICAR: Estudante NÃO pode adicionar flashcards do admin"
echo "   d) Admin cria deck administrativo"  
echo "   e) ✓ VERIFICAR: Admin NÃO pode adicionar flashcards do estudante"
echo "   f) ✓ VERIFICAR: Cada usuário só gerencia seus próprios decks"
echo ""

echo "🔍 PONTOS CRÍTICOS DE VERIFICAÇÃO:"
echo "=================================="
echo "✓ Isolamento total: dados do admin não afetam dados do estudante"
echo "✓ Criação funcional: ambos os usuários criam todos os tipos"
echo "✓ Permissões respeitadas: privado/público funcionando"
echo "✓ Funcionalidades Anki: múltiplas oclusões, import/export"
echo "✓ Interface consistente: mesmo padrão para admin e estudante"
echo "✓ Supervisão admin: pode visualizar mas não editar dados do estudante"
echo ""

echo "🎯 URLs DE TESTE:"
echo "================="
echo "🔧 Admin Decks: http://localhost:5173/admin/flashcards"
echo "🔧 Admin Cards: http://localhost:5173/admin/flashcards/cards"
echo "🔧 Admin New: http://localhost:5173/admin/flashcards/cards/new"
echo "📚 Student Cards: http://localhost:5173/my-flashcards"  
echo "📚 Student New: http://localhost:5173/student/flashcards/new"
echo ""

echo "✨ EXECUTE ESTE ROTEIRO PASSO A PASSO PARA VALIDAÇÃO COMPLETA!"