# Dockerfile para PHP puro
FROM php:8.2-cli

# Instalar dependências do sistema
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

# Limpar cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Instalar extensões PHP necessárias
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Instalar Composer (caso precise no futuro)
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Definir diretório de trabalho
WORKDIR /var/www/html

# Copiar arquivos do projeto
COPY . .

# Install do composer
WORKDIR /var/www/html/public
RUN composer install --no-interaction

# Voltar ao diretório raiz
WORKDIR /var/www/html

# Expor porta
EXPOSE 8000

# Comando para iniciar o servidor PHP built-in
CMD ["php", "-S", "0.0.0.0:8000", "-t", "public"]