-- Script para inserir cursos de exemplo
-- Usando o ID do admin como instructor_id

-- Curso 1: Matemática para Concursos
INSERT INTO courses (
    title,
    slug,
    description,
    category,
    instructor_id,
    thumbnail_url,
    price,
    status,
    visibility,
    difficulty_level,
    duration_hours,
    duration_months,
    language,
    requirements,
    objectives,
    target_audience,
    certification_available,
    published_at
) VALUES (
    'Matemática para Concursos Públicos',
    'matematica-concursos-publicos',
    'Curso completo de matemática focado em concursos públicos. Aborda todos os tópicos essenciais: conjuntos numéricos, operações básicas, frações, porcentagem, regra de três, equações, geometria, estatística e raciocínio lógico.',
    'Concursos',
    '123e4567-e89b-12d3-a456-426614174000',
    'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=800',
    199.90,
    'published',
    'public',
    'intermediate',
    120,
    4,
    'pt-BR',
    ARRAY['Conhecimento básico de matemática', 'Dedicação de pelo menos 1 hora por dia'],
    ARRAY['Dominar matemática para concursos', 'Resolver questões de provas anteriores', 'Desenvolver raciocínio lógico', 'Aprender técnicas de resolução rápida'],
    'Candidatos a concursos públicos de nível médio e superior',
    true,
    NOW()
);

-- Curso 2: Português e Redação
INSERT INTO courses (
    title,
    slug,
    description,
    category,
    instructor_id,
    thumbnail_url,
    price,
    status,
    visibility,
    difficulty_level,
    duration_hours,
    duration_months,
    language,
    requirements,
    objectives,
    target_audience,
    certification_available,
    published_at
) VALUES (
    'Português e Redação para Concursos',
    'portugues-redacao-concursos',
    'Domine a língua portuguesa e redação oficial. Gramática completa, interpretação de textos, novo acordo ortográfico e técnicas de redação para concursos públicos.',
    'Concursos',
    '123e4567-e89b-12d3-a456-426614174000',
    'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800',
    179.90,
    'published',
    'public',
    'intermediate',
    100,
    3,
    'pt-BR',
    ARRAY['Ensino médio completo', 'Vontade de aprender'],
    ARRAY['Dominar gramática e ortografia', 'Interpretar textos complexos', 'Escrever redações nota máxima', 'Conhecer pegadinhas de provas'],
    'Candidatos a concursos públicos e vestibulares',
    true,
    NOW()
);

-- Curso 3: Direito Constitucional
INSERT INTO courses (
    title,
    slug,
    description,
    category,
    instructor_id,
    thumbnail_url,
    price,
    status,
    visibility,
    difficulty_level,
    duration_hours,
    duration_months,
    language,
    requirements,
    objectives,
    target_audience,
    certification_available,
    published_at
) VALUES (
    'Direito Constitucional Descomplicado',
    'direito-constitucional-descomplicado',
    'Aprenda Direito Constitucional de forma clara e objetiva. Constituição Federal completa, princípios fundamentais, direitos e garantias, organização do Estado e dos Poderes.',
    'Direito',
    '123e4567-e89b-12d3-a456-426614174000',
    'https://images.unsplash.com/photo-1589994965851-a8f479c573a9?w=800',
    249.90,
    'published',
    'public',
    'advanced',
    80,
    3,
    'pt-BR',
    ARRAY['Ensino médio completo', 'Noções básicas de direito'],
    ARRAY['Compreender a Constituição Federal', 'Resolver questões de concursos', 'Entender jurisprudência do STF', 'Aplicar conhecimentos na prática'],
    'Estudantes de Direito, candidatos a concursos e profissionais da área',
    true,
    NOW()
);

-- Curso 4: Informática para Concursos
INSERT INTO courses (
    title,
    slug,
    description,
    category,
    instructor_id,
    thumbnail_url,
    price,
    status,
    visibility,
    difficulty_level,
    duration_hours,
    duration_months,
    language,
    requirements,
    objectives,
    target_audience,
    certification_available,
    published_at
) VALUES (
    'Informática Completa para Concursos',
    'informatica-completa-concursos',
    'Tudo sobre informática para concursos: Windows, Linux, pacote Office, LibreOffice, Internet, segurança da informação e conceitos de hardware e software.',
    'Tecnologia',
    '123e4567-e89b-12d3-a456-426614174000',
    'https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=800',
    159.90,
    'published',
    'public',
    'beginner',
    60,
    2,
    'pt-BR',
    ARRAY['Conhecimento básico de computador', 'Acesso a um computador para prática'],
    ARRAY['Dominar conceitos de informática', 'Conhecer sistemas operacionais', 'Usar pacotes de escritório', 'Entender segurança digital'],
    'Candidatos a concursos públicos de todas as áreas',
    true,
    NOW()
);

-- Curso 5: Raciocínio Lógico
INSERT INTO courses (
    title,
    slug,
    description,
    category,
    instructor_id,
    thumbnail_url,
    price,
    status,
    visibility,
    difficulty_level,
    duration_hours,
    duration_months,
    language,
    requirements,
    objectives,
    target_audience,
    certification_available,
    published_at
) VALUES (
    'Raciocínio Lógico e Matemático',
    'raciocinio-logico-matematico',
    'Desenvolva seu raciocínio lógico com questões práticas. Lógica proposicional, argumentação, sequências, probabilidade e análise combinatória.',
    'Concursos',
    '123e4567-e89b-12d3-a456-426614174000',
    'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800',
    189.90,
    'published',
    'public',
    'intermediate',
    90,
    3,
    'pt-BR',
    ARRAY['Matemática básica', 'Pensamento analítico'],
    ARRAY['Resolver problemas lógicos', 'Dominar lógica proposicional', 'Calcular probabilidades', 'Analisar argumentos'],
    'Candidatos a concursos, vestibulares e processos seletivos',
    true,
    NOW()
);

-- Curso 6: Administração Pública
INSERT INTO courses (
    title,
    slug,
    description,
    category,
    instructor_id,
    thumbnail_url,
    price,
    status,
    visibility,
    difficulty_level,
    duration_hours,
    duration_months,
    language,
    requirements,
    objectives,
    target_audience,
    certification_available,
    published_at
) VALUES (
    'Administração Pública para Concursos',
    'administracao-publica-concursos',
    'Conceitos fundamentais de administração pública, princípios administrativos, licitações, contratos, serviços públicos e responsabilidade fiscal.',
    'Administração',
    '123e4567-e89b-12d3-a456-426614174000',
    'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800',
    219.90,
    'published',
    'public',
    'intermediate',
    70,
    2,
    'pt-BR',
    ARRAY['Ensino médio completo', 'Interesse em gestão pública'],
    ARRAY['Entender a máquina pública', 'Conhecer leis administrativas', 'Dominar processos licitatórios', 'Compreender controle e fiscalização'],
    'Candidatos a concursos públicos e servidores',
    true,
    NOW()
);

-- Curso 7: Inglês para Concursos
INSERT INTO courses (
    title,
    slug,
    description,
    category,
    instructor_id,
    thumbnail_url,
    price,
    status,
    visibility,
    difficulty_level,
    duration_hours,
    duration_months,
    language,
    requirements,
    objectives,
    target_audience,
    certification_available,
    published_at
) VALUES (
    'Inglês Instrumental para Concursos',
    'ingles-instrumental-concursos',
    'Aprenda inglês focado em provas de concursos. Interpretação de textos, gramática essencial, vocabulário técnico e estratégias de resolução.',
    'Idiomas',
    '123e4567-e89b-12d3-a456-426614174000',
    'https://images.unsplash.com/photo-1543165365-05141b0ee2b4?w=800',
    169.90,
    'published',
    'public',
    'beginner',
    80,
    3,
    'pt-BR',
    ARRAY['Inglês básico', 'Dedicação para estudos diários'],
    ARRAY['Interpretar textos em inglês', 'Dominar gramática essencial', 'Ampliar vocabulário técnico', 'Resolver questões de provas'],
    'Candidatos a concursos que exigem inglês',
    true,
    NOW()
);

-- Curso 8: Contabilidade Pública
INSERT INTO courses (
    title,
    slug,
    description,
    category,
    instructor_id,
    thumbnail_url,
    price,
    status,
    visibility,
    difficulty_level,
    duration_hours,
    duration_months,
    language,
    requirements,
    objectives,
    target_audience,
    certification_available,
    published_at
) VALUES (
    'Contabilidade Pública Essencial',
    'contabilidade-publica-essencial',
    'Fundamentos de contabilidade aplicada ao setor público. Orçamento público, receitas, despesas, balanços e demonstrações contábeis.',
    'Contabilidade',
    '123e4567-e89b-12d3-a456-426614174000',
    'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800',
    239.90,
    'published',
    'public',
    'advanced',
    100,
    4,
    'pt-BR',
    ARRAY['Noções de contabilidade', 'Conhecimento básico de administração'],
    ARRAY['Entender contabilidade pública', 'Analisar demonstrações contábeis', 'Compreender orçamento público', 'Aplicar normas contábeis'],
    'Contadores, administradores e candidatos a concursos da área fiscal',
    true,
    NOW()
);

-- Atualizar estatísticas dos cursos (opcional)
UPDATE courses SET 
    total_enrollments = FLOOR(RANDOM() * 500 + 100)::integer,
    average_rating = (RANDOM() * 1.5 + 3.5)::numeric(2,1)
WHERE status = 'published';