#!/bin/bash

echo "🎯 TESTE COMPLETO - SISTEMA DE FLASHCARDS PARA ESTUDANTES"
echo "========================================================="
echo ""

# Verificar se o servidor está rodando
if ! curl -s http://localhost:5173 > /dev/null; then
    echo "❌ ERRO: Frontend não está rodando em localhost:5173"
    echo "Execute: cd frontend && npm run dev"
    exit 1
fi

echo "✅ Frontend rodando em http://localhost:5173"
echo ""

echo "📋 ROTEIRO DE TESTES COMPLETO"
echo "============================="
echo ""

echo "1️⃣ TESTE DE ACESSO - ESTUDANTE:"
echo "   a) Faça login como estudante (aluno@example.com / aluno123)"
echo "   b) Verifique se aparece 'MEU ARSENAL' na sidebar"
echo "   c) Clique em 'MEU ARSENAL' -> deve abrir /my-flashcards"
echo ""

echo "2️⃣ TESTE DE CRIAÇÃO DE FLASHCARDS:"
echo "   a) Na página 'MEU ARSENAL', clique em 'CRIAR FLASHCARD'"
echo "   b) Teste todos os 7 tipos de flashcard:"
echo "      - 🔵 BÁSICO (Frente/Verso)"
echo "      - 🟢 BÁSICO INVERTIDO"
echo "      - 🟡 LACUNAS (Cloze) - use {{c1::palavra}}"
echo "      - 🟣 MÚLTIPLA ESCOLHA"
echo "      - 🔴 VERDADEIRO/FALSO"
echo "      - 🟦 DIGITE RESPOSTA"
echo "      - 🟠 OCLUSÃO DE IMAGEM"
echo "   c) Teste o botão 'CARREGAR EXEMPLO' para cada tipo"
echo "   d) Configure visibilidade: PRIVADO vs PÚBLICO"
echo "   e) Salve o flashcard"
echo ""

echo "3️⃣ TESTE DE GESTÃO DE FLASHCARDS:"
echo "   a) Visualize flashcards em modo grid e lista"
echo "   b) Use filtros: busca, dificuldade, status"
echo "   c) Teste ações: Preview, Editar, Ocultar/Publicar, Excluir"
echo "   d) Verifique contadores de stats no topo"
echo ""

echo "4️⃣ TESTE DE IMPORT/EXPORT ANKI:"
echo "   a) Clique na aba 'IMPORTAR/EXPORTAR'"
echo "   b) Teste importação com arquivo: /tmp/test_deck.apkg"
echo "   c) Teste exportação nos 4 formatos:"
echo "      - JSON, CSV, ANKI, .APKG"
echo "   d) Verifique que flashcards importados ficam como PRIVADO"
echo ""

echo "5️⃣ TESTE DE ESTUDO:"
echo "   a) Clique em 'ESTUDAR TODOS' na página"
echo "   b) Teste o modal de estudo interativo"
echo "   c) Verifique navegação entre cards"
echo "   d) Teste botões 'Acertei/Errei'"
echo ""

echo "6️⃣ TESTE DE PERMISSÕES - ADMIN:"
echo "   a) Faça logout e login como admin"
echo "   b) Vá para: /admin/flashcards/cards"
echo "   c) Verifique filtro 'AUTOR' nos filtros"
echo "   d) Filtre por autor específico"
echo "   e) Verifique que admin vê author_name nos cards"
echo "   f) Confirme que admin NÃO pode editar flashcards de estudantes"
echo ""

echo "7️⃣ TESTE DE VISIBILIDADE:"
echo "   a) Como estudante, crie flashcard PRIVADO"
echo "   b) Como estudante, crie flashcard PÚBLICO"
echo "   c) Como admin, verifique que vê ambos com filtros"
echo "   d) Como outro estudante, confirme que só vê os PÚBLICOS"
echo ""

echo "8️⃣ TESTE DE INTEGRAÇÃO COMPLETA:"
echo "   a) Importe flashcards do Anki"
echo "   b) Edite alguns importados"
echo "   c) Crie um deck com eles"
echo "   d) Exporte o deck completo"
echo "   e) Teste sessão de estudo completa"
echo ""

echo "🔍 PONTOS DE VERIFICAÇÃO IMPORTANTES:"
echo "===================================="
echo ""
echo "✓ Estudantes só veem/editam seus próprios flashcards"
echo "✓ Admin pode filtrar e visualizar flashcards de qualquer usuário"
echo "✓ Flashcards PRIVADOS só visíveis para o criador"
echo "✓ Flashcards PÚBLICOS visíveis para todos"
echo "✓ Import/export funcional nos 4 formatos"
echo "✓ Sistema de estudo com SRS funcional"
echo "✓ Todos os 7 tipos de flashcard implementados"
echo "✓ Interface tática/militar consistente"
echo ""

echo "🎯 URLs IMPORTANTES PARA TESTE:"
echo "==============================="
echo "📚 Página do Estudante: http://localhost:5173/my-flashcards"
echo "➕ Criar Flashcard: http://localhost:5173/student/flashcards/new"
echo "🛡️ Admin Flashcards: http://localhost:5173/admin/flashcards/cards"
echo "🏠 Dashboard Estudante: http://localhost:5173/dashboard"
echo "🔧 Admin Dashboard: http://localhost:5173/admin/dashboard"
echo ""

echo "📁 ARQUIVOS DE TESTE CRIADOS:"
echo "============================="
echo "• /tmp/test_deck.apkg - Arquivo teste para importação"
echo "• /tmp/test_flashcards.json - JSON de exemplo"
echo ""

echo "✨ SISTEMA PRONTO PARA TESTES COMPLETOS!"
echo ""
echo "Para iniciar os testes, acesse: http://localhost:5173"