[package]
name = "estudos-backend-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web Framework (minimal)
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
tower = "0.4"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Utilities
chrono = { version = "0.4", features = ["serde"] }

# Environment
dotenv = "0.15"