version: '3.8'

services:
  backend-rust:
    build: .
    container_name: estudos-backend-rust
    ports:
      - "8181:8180"  # Different port to avoid conflicts with PHP backend
    environment:
      - DATABASE_URL=postgresql://estudos_user:estudos_pass@postgres:5432/estudos_db
      - RUST_LOG=info
      - RUST_ENV=development
      - JWT_SECRET=your-jwt-secret-here
      - PORT=8180
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - estudos-network

  postgres:
    image: postgres:15-alpine
    container_name: estudos-postgres-rust
    environment:
      - POSTGRES_DB=estudos_db
      - POSTGRES_USER=estudos_user
      - POSTGRES_PASSWORD=estudos_pass
    ports:
      - "5533:5432"  # Different port to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../backend/database/schema_postgres.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../backend/database/sample_data.sql:/docker-entrypoint-initdb.d/02-data.sql
    restart: unless-stopped
    networks:
      - estudos-network

volumes:
  postgres_data:
    driver: local

networks:
  estudos-network:
    driver: bridge